### ISSUE TITLE
A2C Environment

### ISSUE THREAD

**Issue by wyciokas** [xuxiyang1993/Multiagent_collision_avoidance#2]
In A2C model "A2C.py" MultiAircraftVertiportA2CEnv is used:
`from MultiAircraftVertiportA2CEnv import MultiAircraftEnv`
However no such environment exist in Simulators directory.

**Comment by xuxiyang1993** [comment]
Thanks for your feedback! I just uploaded `MultiAircraftVertiportA2CEnv.py` under the directory `Simulators/`.

Note this algorithm is not working properly yet. Also the reward function needs to be tuned in config file line 54 https://github.com/xuxiyang1993/Multiagent_collision_avoidance/blob/master/Simulators/config_vertiport.py
